name: readset
on:
  pull_request:

jobs:
  merge-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch the target branch
        run: git fetch origin ${{ github.base_ref }}
      - uses: ./
        with:
          into: origin/${{ github.base_ref }}
